### PR TITLE
Add database structure

### PR DESCRIPTION
**Pull request by Maxopoly**

### CODE REVIEW

**Comment by Maxopoly** [comment]
@ProgrammerDan @Erocs would this be fine as our new standard for databases?

**Comment by ProgrammerDan** [comment]
I would like to employ https://github.com/brettwooldridge/HikariCP actually, but this is a good start.

**Comment by Maxopoly** [comment]
You could make a pull for that or we just use this for now and change it at a later point, most likely we would have to change nothing in the plugins using this.

**Comment by ProgrammerDan** [comment]
yep this is a fine start. What I want to do is a much more major refactor and we just don't have the time for it now, so this is okay.

**Comment by erocs** [comment]
I think I'd rather not have isConnected(). I'm in favor of just attempting
the SQL statement and then reconnecting / retrying if there's a connection
failure. Since you do expose execute, select could also be added and this
class could handle the error.

**Pull request closed without merging**
