### PR TITLE
Replaced CustomConversation with Bukkit API.

### PR DESCRIPTION
**Pull request by goeppes**
#18

I changed the the spigot dependency to the one that BuildTools puts into the local maven repo so that I could build it. Unless they released a new version recently, I think everyone else should have it as well and that it should be preferred to manually putting a spigot jar in. 

Also added a .editorconfig file.

### CODE REVIEW

**Comment by Maxopoly** [comment]
The spigot dependency doesn't have the NMS classes, so it wont build only with the dependency from their nexus (unless they recently changed that). You also forgot to add the repository for it, so right now it definitely wont build.

**Comment by goeppes** [comment]
Well, it built for me.

Are you sure you're not thinking of the spigot API?

**Comment by Maxopoly** [comment]
Yes, I am sure. Look at your current pom:

https://github.com/tyrothalos/CivModCore/blob/master/pom.xml

Where is it supposed to get the dependency from if there is no repository/nexus for it specified?

It probably built for you, because you have that exact spigot dependency installed locally (including nms)

**Comment by goeppes** [comment]
Yes, it is installed locally because I used the Spigot BuildTools. Like I said, if you run BuildTools (for your desired version of Minecraft) it will automatically install the spigot jar into your local maven repo. 

As far as I know there is no external repository to import the spigot jar from because doing so is illegal. The entire reason Spigot made BuildTools was to get around that.

**Comment by Maxopoly** [comment]
No

http://www.spigotmc.org/wiki/spigot-maven/

That one doesnt have NMS though (those would be illegal, but bukkits/spigots stuff isnt)

**Comment by goeppes** [comment]
That's for the Spigot and Bukkit APIs, it says right there in the example. 

Distributing the API (the interface) is not illegal, but distributing the actual spigot server jar (the implementation) is illegal because it contains copyrighted Minecraft code. 

If you want to include NMS stuff in your dependencies, then the preferred way of doing so is to use BuildTools to install the spigot server jar into your local maven repo and then using that in the pom.xml.

**Comment by ProgrammerDan** [comment]
Long story short many of our plugins use a custom named spigot because we use a custom spigot build on our build server.

I tried to get everyone to switch to this notation but no dice :).

For the time being, please revert this PR to the prior dependency; locally feel free to stash the change so it builds fine.

One bright morning you and I will ninja in the correction while everyone else is asleep and they will be none the wiser, but that day is not today.

**Comment by goeppes** [comment]
If you say so...

Where can I find the custom build?

**Comment by ProgrammerDan** [comment]
Sorry, I was unclear.

Locally, build as you are.

For PRs to this repos and others equally ... unique ... leave the dependency as you found it.

The Jar itself is only available to admins. :-/ The changes would be available to everyone if Spigot ever accepted third party PRs...

**Comment by ProgrammerDan** [comment]
@Maxopoly PR looks good. Any issues on your end? If none, feel free to merge.

**Pull request merged**
